//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Prac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitor
    {
        public int Monitor_ID { get; set; }
        public string Monitor_Name { get; set; }
        public Nullable<int> Brand_ID { get; set; }
    
        public virtual Brand Brand { get; set; }
    }
}
